-- Agrega columnas de control a TD_001_RESULTADO_IA
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TD_001_RESULTADO_IA' AND COLUMN_NAME='cdEstadoControl')
BEGIN
	ALTER TABLE TD_001_RESULTADO_IA ADD cdEstadoControl INT NOT NULL CONSTRAINT DF_ResultadoIA_cdEstadoControl DEFAULT 1;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TD_001_RESULTADO_IA' AND COLUMN_NAME='snModificaDatos')
BEGIN
	ALTER TABLE TD_001_RESULTADO_IA ADD snModificaDatos CHAR(2) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TD_001_RESULTADO_IA' AND COLUMN_NAME='feControl')
BEGIN
	ALTER TABLE TD_001_RESULTADO_IA ADD feControl DATETIME NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='TD_001_RESULTADO_IA' AND COLUMN_NAME='cdUsuarioControl')
BEGIN
	ALTER TABLE TD_001_RESULTADO_IA ADD cdUsuarioControl INT NULL;
END
GO

-- Alta de estados de proceso CONTROL en TD_ESTADOS
IF NOT EXISTS (SELECT 1 FROM TD_ESTADOS WHERE dsProceso='CONTROL' AND cdEstado=1)
	INSERT INTO TD_ESTADOS (dsProceso, cdEstado, dsEstado) VALUES ('CONTROL', 1, 'Pendiente de Control');
GO

IF NOT EXISTS (SELECT 1 FROM TD_ESTADOS WHERE dsProceso='CONTROL' AND cdEstado=2)
	INSERT INTO TD_ESTADOS (dsProceso, cdEstado, dsEstado) VALUES ('CONTROL', 2, 'Controlado');
GO

IF NOT EXISTS (SELECT 1 FROM TD_ESTADOS WHERE dsProceso='CONTROL' AND cdEstado=3)
	INSERT INTO TD_ESTADOS (dsProceso, cdEstado, dsEstado) VALUES ('CONTROL', 3, 'Pagina Ilegible');
GO

IF NOT EXISTS (SELECT 1 FROM TD_ESTADOS WHERE dsProceso='CONTROL' AND cdEstado=4)
	INSERT INTO TD_ESTADOS (dsProceso, cdEstado, dsEstado) VALUES ('CONTROL', 4, 'Datos ilegibles');
GO
