<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<UseWindowsForms>true</UseWindowsForms>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="itext7" Version="8.0.5" />
	<PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.5" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	<PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
	<PackageReference Include="PdfiumViewer" Version="2.13.0" />
	<PackageReference Include="PdfiumViewer.Native.x86_64.v8-xfa" Version="2018.4.8.256" />
	<PackageReference Include="System.Drawing.Common" Version="9.0.0" />
	<PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
	<None Include="$(NuGetPackageRoot)pdfiumviewer.native.x86_64.v8-xfa\2018.4.8.256\Build\x64\pdfium.dll">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <Link>pdfium.dll</Link>
	</None>
  </ItemGroup>

</Project>
